// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: api/protobuf/goflake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUUIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUUIDRequest) Reset() {
	*x = GetUUIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_goflake_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUUIDRequest) ProtoMessage() {}

func (x *GetUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_goflake_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetUUIDRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_goflake_proto_rawDescGZIP(), []int{0}
}

type GetUUIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid uint64 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // new UUID
}

func (x *GetUUIDResponse) Reset() {
	*x = GetUUIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_goflake_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUUIDResponse) ProtoMessage() {}

func (x *GetUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_goflake_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetUUIDResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_goflake_proto_rawDescGZIP(), []int{1}
}

func (x *GetUUIDResponse) GetUuid() uint64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

type DecomposeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid uint64 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // UUID to decompose
}

func (x *DecomposeRequest) Reset() {
	*x = DecomposeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_goflake_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecomposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecomposeRequest) ProtoMessage() {}

func (x *DecomposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_goflake_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecomposeRequest.ProtoReflect.Descriptor instead.
func (*DecomposeRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_goflake_proto_rawDescGZIP(), []int{2}
}

func (x *DecomposeRequest) GetUuid() uint64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

type DecomposeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid         string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                     // the uuid of the flake that was decomposed
	Timestamp    string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                           // RFC3339
	DatacenterId string `protobuf:"bytes,3,opt,name=datacenter_id,json=datacenterId,proto3" json:"datacenter_id,omitempty"` // the datacenter id of the flake
	MachineId    string `protobuf:"bytes,4,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`          // the machine id of the flake
	Sequence     string `protobuf:"bytes,5,opt,name=sequence,proto3" json:"sequence,omitempty"`                             // the sequence of the flake
	Msb          bool   `protobuf:"varint,6,opt,name=msb,proto3" json:"msb,omitempty"`                                      // false for 0, true for 1
}

func (x *DecomposeResponse) Reset() {
	*x = DecomposeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_goflake_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecomposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecomposeResponse) ProtoMessage() {}

func (x *DecomposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_goflake_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecomposeResponse.ProtoReflect.Descriptor instead.
func (*DecomposeResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_goflake_proto_rawDescGZIP(), []int{3}
}

func (x *DecomposeResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DecomposeResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *DecomposeResponse) GetDatacenterId() string {
	if x != nil {
		return x.DatacenterId
	}
	return ""
}

func (x *DecomposeResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *DecomposeResponse) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *DecomposeResponse) GetMsb() bool {
	if x != nil {
		return x.Msb
	}
	return false
}

var File_api_protobuf_goflake_proto protoreflect.FileDescriptor

var file_api_protobuf_goflake_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67,
	0x6f, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x6f,
	0x66, 0x6c, 0x61, 0x6b, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x55, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x55,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x26,
	0x0a, 0x10, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0xb7, 0x01, 0x0a, 0x11, 0x44, 0x65, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x23,
	0x0a, 0x0d, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x6d, 0x73, 0x62,
	0x32, 0x94, 0x01, 0x0a, 0x0c, 0x46, 0x6c, 0x61, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x55, 0x49, 0x44, 0x12, 0x17, 0x2e, 0x67,
	0x6f, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x6f, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x44, 0x0a, 0x09, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x19,
	0x2e, 0x67, 0x6f, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x66, 0x6c,
	0x61, 0x6b, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x76, 0x69, 0x65, 0x6c, 0x79, 0x6f, 0x31, 0x30, 0x2f,
	0x67, 0x6f, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protobuf_goflake_proto_rawDescOnce sync.Once
	file_api_protobuf_goflake_proto_rawDescData = file_api_protobuf_goflake_proto_rawDesc
)

func file_api_protobuf_goflake_proto_rawDescGZIP() []byte {
	file_api_protobuf_goflake_proto_rawDescOnce.Do(func() {
		file_api_protobuf_goflake_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protobuf_goflake_proto_rawDescData)
	})
	return file_api_protobuf_goflake_proto_rawDescData
}

var file_api_protobuf_goflake_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_protobuf_goflake_proto_goTypes = []interface{}{
	(*GetUUIDRequest)(nil),    // 0: goflake.GetUUIDRequest
	(*GetUUIDResponse)(nil),   // 1: goflake.GetUUIDResponse
	(*DecomposeRequest)(nil),  // 2: goflake.DecomposeRequest
	(*DecomposeResponse)(nil), // 3: goflake.DecomposeResponse
}
var file_api_protobuf_goflake_proto_depIdxs = []int32{
	0, // 0: goflake.FlakeService.GetUUID:input_type -> goflake.GetUUIDRequest
	2, // 1: goflake.FlakeService.Decompose:input_type -> goflake.DecomposeRequest
	1, // 2: goflake.FlakeService.GetUUID:output_type -> goflake.GetUUIDResponse
	3, // 3: goflake.FlakeService.Decompose:output_type -> goflake.DecomposeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protobuf_goflake_proto_init() }
func file_api_protobuf_goflake_proto_init() {
	if File_api_protobuf_goflake_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protobuf_goflake_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUUIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_goflake_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUUIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_goflake_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecomposeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_goflake_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecomposeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protobuf_goflake_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protobuf_goflake_proto_goTypes,
		DependencyIndexes: file_api_protobuf_goflake_proto_depIdxs,
		MessageInfos:      file_api_protobuf_goflake_proto_msgTypes,
	}.Build()
	File_api_protobuf_goflake_proto = out.File
	file_api_protobuf_goflake_proto_rawDesc = nil
	file_api_protobuf_goflake_proto_goTypes = nil
	file_api_protobuf_goflake_proto_depIdxs = nil
}
